from typing import TypedDict, Optional
from typing_extensions import Annotated
from langgraph.graph.message import add_messages

class ResearchState(TypedDict):
    """
    1. user_query: Initial question from user
    2. research_plan: Sub-questions generated by planner agent
    3. findings: Research results gathered by research agent
    4. final_report: Synthesized analysis from analyst agent
    """
    user_query: str

    research_plan: Optional[str]

    findings: Optional[str]

    final_report: Optional[str]

    messages: Annotated[list, add_messages]