from typing import TypedDict, Optional

class ResearchState(TypedDict):
    """
    State for research assistant pipeline.

    user_query: Initial question from user
    research_plan: Sub-questions generated by planner agent
    findings: Research results gathered by research agent
    fact_check: Fact-check results from fact checker agent
    citations: Formatted citations and bibliography from citation agent
    final_report: Synthesized analysis from analyst agent
    """
    user_query: str
    research_plan: Optional[str]
    findings: Optional[str]
    fact_check: Optional[str]
    citations: Optional[str]
    final_report: Optional[str]